/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Color;
import Sesion3.Salpicadero;

/**
 *
 * @author pablo
 */
public class panel extends javax.swing.JPanel {
    public int EstadoMotor;
    private Salpicadero salpicadero;
    private Boolean ON=false;
    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }
    
    public void setSalpicadero(Salpicadero sal){
        salpicadero = sal;
    }
    
    public Salpicadero getSalpicadero(){
        return salpicadero ;
    }
    public int getEstado(){
        return EstadoMotor;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOnOff = new javax.swing.JTextField();
        mandos = new javax.swing.JLabel();
        EncenderApagar = new javax.swing.JToggleButton();
        Acelerar = new javax.swing.JToggleButton();
        Frenar = new javax.swing.JToggleButton();

        panelOnOff.setText("APAGADO");
        panelOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelOnOffActionPerformed(evt);
            }
        });

        mandos.setText("mandos");

        EncenderApagar.setForeground(new java.awt.Color(0, 255, 0));
        EncenderApagar.setText("Encender");
        EncenderApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EncenderApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncenderApagarActionPerformed(evt);
            }
        });

        Acelerar.setText("Acelerar");
        Acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcelerarActionPerformed(evt);
            }
        });

        Frenar.setText("Frenar");
        Frenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(panelOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(mandos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(EncenderApagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(Acelerar)
                .addGap(35, 35, 35)
                .addComponent(Frenar)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mandos)
                .addGap(52, 52, 52)
                .addComponent(panelOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncenderApagar)
                    .addComponent(Acelerar)
                    .addComponent(Frenar))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelOnOffActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelOnOffActionPerformed

    private void EncenderApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncenderApagarActionPerformed
        // TODO add your handling code here:
        if(EncenderApagar.isSelected()){
            EncenderApagar.setText("Apagar");
            EncenderApagar.setForeground(new java.awt.Color(255, 0, 0));
            panelOnOff.setText("Encendido");
            panelOnOff.setForeground(Color.red);
            EstadoMotor= 3;
            salpicadero.setEstado(EstadoMotor);
            ON=true;
        }else{
            EncenderApagar.setText("Encender");
            EncenderApagar.setForeground(new java.awt.Color(0, 255, 0));
            panelOnOff.setText("Apagado");
            panelOnOff.setForeground(Color.red);
            EstadoMotor=2;
            salpicadero.setEstado(EstadoMotor);
            ON=false;
        }
    }//GEN-LAST:event_EncenderApagarActionPerformed

    private void FrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenarActionPerformed
        // TODO add your handling code here:
         if (ON){
             if(Acelerar.isSelected() == false){
                if (Frenar.isSelected()){
                    
                    panelOnOff.setText("Frenando");
                    panelOnOff.setForeground(Color.red);
                    Frenar.setText("Soltar Freno");
                    Frenar.setForeground(Color.red);
                    EstadoMotor=1;
                    salpicadero.setEstado(EstadoMotor);
                }else{
                    panelOnOff.setText("Encendido");
                    panelOnOff.setForeground(Color.red);
                    Frenar.setText("Frenar");
                    Frenar.setForeground(Color.black);
                    EstadoMotor=3;
                    salpicadero.setEstado(EstadoMotor);
                }
            }
        }
    }//GEN-LAST:event_FrenarActionPerformed

    private void AcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcelerarActionPerformed
        // TODO add your handling code here:
         if (ON){
            if(Frenar.isSelected() == false){
                if (Acelerar.isSelected()){
                    
                    panelOnOff.setText("Acelerando");
                    panelOnOff.setForeground(Color.red);
                    Acelerar.setText("Soltar Acelerador");
                    Acelerar.setForeground(Color.red);
                    EstadoMotor=0;
                    salpicadero.setEstado(EstadoMotor);
                    
                    
                }else{
                    
                    panelOnOff.setText("Encendido");
                    panelOnOff.setForeground(Color.red);
                    Acelerar.setText("Acelerar");
                    Acelerar.setForeground(Color.black);
                    EstadoMotor=3;
                    salpicadero.setEstado(EstadoMotor);
                }
            }
        }
    }//GEN-LAST:event_AcelerarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Acelerar;
    private javax.swing.JToggleButton EncenderApagar;
    private javax.swing.JToggleButton Frenar;
    private javax.swing.JLabel mandos;
    private javax.swing.JTextField panelOnOff;
    // End of variables declaration//GEN-END:variables
}
