/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sesion3;
import GUI.*;
import java.util.Scanner;
import java.time.LocalDate;


public class Main extends javax.swing.JFrame  {
    static Salpicadero salpicadero = new Salpicadero();
    static GestorDeFiltro gestor = new GestorDeFiltro();
    static SalpicaderoGUI panelSalpicadero ;
    static int EstadoSCACV;
    
    // EstadoMotor = 0 -> Acelerando
    // EstadoMotor = 1 -> Frenando
    // EstadoMotor = 2 -> Apagado
    // EstadoMotor = 3 -> Encendido
    // EstadoSCACV = 0 -> Acelerar
    // EstadoSCACV = 1 -> Mantener
    // EstadoSCACV = 2 -> Reiniciar
    // EstadoSCACV = 3 -> Apagar
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents(); 
        panel2.setSalpicadero(salpicadero);
        //salpicadero = panel2.getSalpicadero();
        repaint();
        revalidate();
         
    }
    
    static private void esperarXsegundos(int segundos) {
		try {
			Thread.sleep(segundos * 1000);
		} catch (InterruptedException ex) {
			Thread.currentThread().interrupt();
		}
	}

    public void ActualizarV(){
      //  salpicaderoGUI1.actualizarVista(salpicadero);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new GUI.panel();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new GUI.panel();
        contenedorSalpicadero = new GUI.SalpicaderoGUI();
        sCACVGUI1 = new GUI.SCACVGUI();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(contenedorSalpicadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(sCACVGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contenedorSalpicadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(sCACVGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //double r = 0;
        gestor.peticionFiltros();
        
        System.out.println("Inside : " + Thread.currentThread().getName());

        System.out.println("Creating Runnable...");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                  double r = 0.0;
                
                  System.out.println("Inside : " + Thread.currentThread().getName());
                  while(true){
                     // System.out.println("estado es ");
                      //int estado = salpicadero.getEstado();
                      esperarXsegundos(1);
                     
                      
                      r = gestor.ejecutar(r, salpicadero.getEstado(), salpicadero, sCACVGUI1.getEstadoSCACV());
                      salpicadero.setDistancias(salpicadero.getVelocidad()/3600.0);
                      if (salpicadero.getEstado() == 2){
                          salpicadero.reiniciarDistRec();
                      }
                      
                      contenedorSalpicadero.actualizarVista(salpicadero);
                      sCACVGUI1.actualizarVista(gestor.getUltimoConocido(), r);
                      
                  }
            }
        };

        System.out.println("Creating Thread...");
        Thread thread = new Thread(runnable);

        System.out.println("Starting Thread...");
        thread.start();
        
       
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
        
        
           //  Scanner teclado= new Scanner(System.in);
           //  int estado = teclado.nextInt();
            
            
            
            
               
               
              // thread.run();
              
               
               
               
               
            
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static GUI.SalpicaderoGUI contenedorSalpicadero;
    private javax.swing.JPanel jPanel1;
    private GUI.panel panel1;
    public GUI.panel panel2;
    public static GUI.SCACVGUI sCACVGUI1;
    // End of variables declaration//GEN-END:variables
}


